#pragma once

struct ServerPlayersController;
struct Client;
struct PlayerProfile;

enum E_MODE
{
	E_MODE_NULL = 4294967295, 
	E_MODE_BATTLE = 0, 
	E_MODE_CLASSIC = 1, 
	E_MODE_BUILD = 2, 
	E_MODE_ZOMBIE = 3, 
	E_MODE_CAPTURE = 4, 
	E_MODE_CONTRA = 5, 
	E_MODE_MELEE = 6, 
	E_MODE_SURVIVAL = 7, 
	E_MODE_M1945 = 8, 
	E_MODE_PRORIV = 9, 
	E_MODE_CLEAR = 10, 
	E_MODE_TANK = 11, 
	E_MODE_SNOWBALLS = 12, 
	E_MODE_FFA = 13, 
	E_MODE_GUNGAME = 14, 
	E_MODE_MUTAGEN = 15, 
	E_MODE_SEASON1 = 16, 
	E_MODE_ANARCHY = 17, 
};

enum E_GS
{
	GS_LOADING = 0,
	GS_STARTING = 1,
	GS_GLOBAL_INIT = 2,
	GS_PLATFORM_INIT = 3,
	GS_EOS_CONNECT = 4,
	GS_EOS_SANCTIONS_CHECK = 5,
	GS_GET_GAME_DATA = 6,
	GS_GET_PLATFORM_PLAYER_ID = 7,
	GS_GET_PLATFORM_TOKEN = 8,
	GS_GET_PLAYER_PROFILE = 9,
	GS_GET_SESSION = 10,
	GS_GET_FRIENDS_RATING = 11,
	GS_GET_FRIENDS_ONLINE = 12,
	GS_GAME_AUTH = 13,
	GS_LOAD_MAINMENU = 14,
	GS_WAITING_FOR_LOADING_BUNDLES = 15,
	GS_WAITING_FOR_EOS_INIT = 16,
	GS_WAITING_FOR_EOS_CONNECT = 17,
	GS_WAITING_FOR_EOS_SANCTIONS_CHECK = 18,
	GS_WAITING_FOR_LOADING_AUTH_SCENE = 19,
	GS_WAITING_FOR_LOADING_MAINMENU_SCENE = 20,
	GS_WAITING_FOR_GAME_DATA = 21,
	GS_WAITING_FOR_PLATFORM_INIT = 22,
	GS_WAITING_FOR_PLATFORM_PLAYER_ID = 23,
	GS_WAITING_FOR_PLATFORM_LOGIN = 24,
	GS_WAITING_FOR_PLATFORM_TOKEN = 25,
	GS_WAITING_FOR_CHECK_PLATFORM_TOKEN = 26,
	GS_WAITING_FOR_AUTH_KEY = 27,
	GS_WAITING_FOR_GAME_AUTH = 28,
	GS_WAITING_FOR_PLAYER_PROFILE = 29,
	GS_MAINMENU = 30,
	GS_CONNECTING = 31,
	GS_GAME = 32,
	GS_GAMEMENU = 33,
	GS_BREAK = 34,
	GS_GAME_LOADING_MAP = 35,
	GS_GAME_LOADING_MAP_CHANGES = 36,
	GS_GAME_LOADING_MY_PROFILE = 37,
	GS_GAME_VISUALIZING_MAP = 38,
	GS_EOS_CONNECT_COMPLITE = 39,
	GS_EOS_SANCTIONS_CHECK_COMPLITE = 40,
	GS_GET_PLATFORM_PLAYER_ID_COMPLITE = 41,
	GS_LOAD_PROFILE_COMLITE = 42,
	GS_LOAD_BUNDLES_COMLITE = 43,
	GS_GET_GAME_DATA_COMPLITE = 44,
	GS_GET_SESSION_COMLITE = 45,
	GS_GET_SOCIAL_DATA_COMPLITE = 46,
	GS_GET_FRIENDS_RATING_COMLITE = 47,
	GS_GET_FRIENDS_ONLINE_COMLITE = 48,
	GS_GET_PLATFORM_TOKEN_COMLITE = 49,
	GS_GAME_AUTH_COMPLITE = 50,
	GS_GAME_LOAD_MAP_COMPLITE = 51,
	GS_GAME_LOAD_MAP_CHANGES_COMPLITE = 52,
	GS_GAME_LOAD_MY_PROFILE_COMPLITE = 53,
	GS_GAME_VISUALIZING_MAP_COMPLITE = 54,
	GS_SERVER_UPDATES = 55,
	GS_GAME_AUTH_ERROR = 56,
	GS_LOADING_PROFILE_ERROR = 57,
	GS_GET_SESSION_ERROR = 58,
	GS_LOADING_BUNDLE_ERROR = 59,
	GS_GET_FRIENDS_RATING_ERROR = 60,
	GS_GET_FRIENDS_ONLINE_ERROR = 61,
	GS_GET_PLATFORM_TOKEN_ERROR = 62,
	GS_CLIENT_INIT_ERROR = 63,
	GS_EOS_CONNECT_ERROR = 64,
	GS_EOS_SANCTIONS_CHECK_ERROR = 65,
	GS_BANNED = 66,
	GS_GET_ID_ERROR = 67,
	GS_NULL = 68,
};

namespace game {
	void initialize();

	ServerPlayersController* get_pcontroller();
	Client* get_client();
	uintptr get_send_packet();
	uintptr get_map();
	uintptr get_packetcmds_fields();
	PlayerProfile* get_profile();
	E_MODE get_mode();
	E_GS get_gs();
};

